### ISSUE TITLE
Destination directory /home/aur_builder/.gnupg does not exist

### ISSUE THREAD

**Issue by ondrish** [Madic-/Sway-DE#10]
Hello, 

I tried to run this in a VM with KDE installed, logged out and with no DM. 

when running setup-02 i get:
TASK [Arch | Making sure file ~/.gnupg/gpg.conf exists for user aur_builder] *********************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "msg": "Destination directory /home/aur_builder/.gnupg does not exist"}

PLAY RECAP ***************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=4    changed=2    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by ondrish** [comment]
manually creating the missing file solves the issue

**Comment by madic-creates** [comment]
Fixed
