### ISSUE TITLE
Consider using SwayNC instead of Mako

### ISSUE THREAD

**Issue by tukusejssirs** [Madic-/Sway-DE#12]
I think that [SwayNC](https://github.com/ErikReider/SwayNotificationCenter) is superior to Mako. It is more of a notification _centre_, as it auto-hides notifications after pre-configured time and you can access the notification centre via a keyboard shortcut or via custom Waybar module.

**Comment by madic-creates** [comment]
I tested swaync the last few days and it's too much for me. I don't require a notification centre. For me notifications are mostly "see and forget". swaync requires that I begin to "manage" my notifications, at least a bit.
