### ISSUE TITLE
swayidle service j2 config error

### ISSUE THREAD

**Issue by runwu2012** [Madic-/Sway-DE#17]
systemd/user/swayidle.service.j2 config file has error config ,line 8 has a multi start Text "ExecStart="

**Comment by madic-creates** [comment]
Thank you. If you want create a merge requests and I will approve it. If not I fix it next week when I'm back on my workstation

**Comment by madic-creates** [comment]
Fixed in https://github.com/Madic-/Sway-DE/commit/396562c028d3c6ffe0d2b2765be9172217896f08
