### ISSUE TITLE
Gammastep not working

### ISSUE THREAD

**Issue by IzhakJakov** [Madic-/Sway-DE#7]
Is this a know issue?
If not, let me know what you need me to provide

**Comment by madic-creates** [comment]
It's a known issue. I had debugged it in the past but wasn't able to resolve it. Maybe I try it again next week and collect my findings in this issue. There were some problems visible via dmesg but I can't remember

**Comment by IzhakJakov** [comment]
#### Thanks you!  

---

I eventually got `gammastep` itself to work like this:
```
bindsym $mod+Shift+b exec pkill -USR1 gammastep || gammastep -O 2000
```
However, it might be a bit buggy still.
Moreover, I am still unable to add `gammastep-indicator` to my notification area.  

_**Note:**_ _I am very new to Sway and never used i3 so I might not be doing this correctly_

---

### Since this might be a real issue, here are some more details:
#### Operating System
```
 =>> cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
```
#### Sway Version
```
 =>> sway -v
sway version v1.5
```
#### Gammastep Version
```
=>> gammastep -V
gammastep 2.0.2
```
#### Gammastep works when I run this command
```
gammastep -O 2200 2>/dev/null &
```

If you there is something you can think about that you want me to provide, just let me know

**Comment by madic-creates** [comment]
I've tested gammastep again and it seems to work.

For gammastep-indicator: If you're using waybar you need to start waybar with the env variable XDG_CURRENT_DESKTOP=Unity and install the package libappindicator-gtk3 (Arch). I think the debian package name is libappindicator3-1.
For the env variable you can take a look at my [waybar systemd unit](https://github.com/Madic-/Sway-DE/blob/master/config/systemd/user/waybar.service.j2).

And I'm starting gammaste-indicator with the following parameters:
```
/usr/bin/gammastep-indicator -l ${RS_LAT}:${RS_LON} -m wayland -t ${RS_DAY}:${RS_NIGHT}
```
An [explanation for the variables](https://github.com/Madic-/Sway-DE#gammastep) is in the readme.

It's also important to start gammastep with "-m wayland".

The gammastep-indicator can be automatically started if you paste the comand into your sway config, prepending it with "exec".
```
exec /usr/bin/gammastep-indicator -l ${RS_LAT}:${RS_LON} -m wayland -t ${RS_DAY}:${RS_NIGHT}
```
